### ISSUE TITLE
Instalar o pacote vegan

### ISSUE THREAD

**Issue by msversutdias** [msversutdias/PrimeiroContatoGITHUB#14]
@ArllenPaumgartten instala o pacote vegan e coloca isso tudo lá no readme.md.
Depois carregar o pactoe no analises.R

- [x] instalar o pacote
- [x] carregar o pacote @jelchamusca 
- [x] baixar os dados @Kamilla-Ramos 
- [x] rodar a RDA @YaraBallarini

**Comment by silrodrigues** [comment]
rodei a RDA
